Bowwing-Return-System/myproject/myapp/urls.py
from django.urls import path
from myapp import views  # Import your views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", views.home, name="home"),
    path("registor/", views.registor, name="registor"),
    path("login/", views.user_login, name="login"),
    path("catalog_user/", views.catalog_user, name="catalog_user"),
    path("catalog_staff/", views.catalog_staff, name="catalog_staff"),
    path("catalog_staff/<equipment_id>", views.return_item, name="return_item"),
    path("catalog_admin/", views.catalog_admin, name="catalog_admin"),
    path("user_borrowing/<equipment_id>", views.borrow_view, name="borrow_request"),
    path("home_staff/", views.home_staff, name="home_staff"),
    path("approval_staff/", views.approval_staff, name="approval_staff"),
    path("approval_staff/<borrow_id>", views.borrow_pass, name="borrow_pass"),
    path("history_staff/", views.history_staff, name="history_staff"),
    path("home_user/", views.home_user, name="home_user"),
    path("logout/", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    path("edit_admin/", views.edit_admin, name="edit_admin"),
    path("home_admin/", views.home_admin, name="home_admin"),
    path("report_admin/", views.report_admin, name="report_admin"),
    path("history_admin/", views.history_admin, name="history_admin"),
    path("edit_admin/<int:equipment_id>/", views.edit_admin, name="edit_admin"),
<<<<<<< HEAD
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("reset-password/<str:token>/", views.reset_password, name="reset_password"),
=======
    path("catalog_admin/<int:equipment_id>/", views.delete_item, name="delete_item"),
    path("add_item/", views.add_item, name="add_item"),
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bowwing-Return-System/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls")),
]

Bowwing-Return-System/myproject/myapp/models.py
from django.db import models
from django.core.exceptions import ValidationError
<<<<<<< HEAD
from django.utils import timezone
import uuid

=======
from django.db.backends.signals import connection_created
from django.dispatch import receiver
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

class Student(models.Model):
    student_id = models.AutoField(primary_key=True)
    fullname = models.CharField(max_length=100)
<<<<<<< HEAD
    username = models.CharField(max_length=100)
    kkumail = models.EmailField(max_length=100)
=======
    username = models.CharField(max_length=100, unique=True)
    kkumail = models.EmailField(max_length=100, unique=True)
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540
    phone = models.CharField(max_length=17)
    password = models.CharField(max_length=20)
    student_id_edu = models.CharField(max_length=10)
    major = models.CharField(max_length=100)
    last_login = models.DateTimeField(null=True, blank=True)

    def __str__(self):
<<<<<<< HEAD
        return f"Fullname: {self.fullname}, Usename: {self.username}, Phone number: {self.phone}"

=======
        return self.kkumail
    
    @property
    def is_authenticated(self):
        return True
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

class Staff(models.Model):
    staff_id = models.AutoField(primary_key=True)
    fullname = models.CharField(max_length=100)
<<<<<<< HEAD
    username = models.CharField(max_length=100, unique=True)
    kkuemail = models.EmailField(max_length=100, unique=True)
=======
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540
    phone = models.CharField(max_length=17)
    password = models.CharField(max_length=20)
    employee_id = models.CharField(max_length=10)
    last_login = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.email
    
    @property
    def is_authenticated(self):
        return True

class Admin(models.Model):
    admin_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100, default="admin")
    email = models.EmailField(max_length=100, default="admin@kku.ac.th")
    password = models.CharField(max_length=20, default="admin1234")
<<<<<<< HEAD


class Status(models.Model):
    name = models.CharField(max_length=100)
=======
    last_login = models.DateTimeField(null=True, blank=True)
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

    def __str__(self):
        return self.email
    
    @property
    def is_authenticated(self):
        return True

class Equipment(models.Model):
    equipment_id = models.AutoField(primary_key=True)
    image = models.ImageField(upload_to="images/", default="media/images/default.jpg")
    name = models.CharField(max_length=100)
    parcel_id = models.CharField(max_length=20)
    brand = models.CharField(max_length=100)
    status = models.BooleanField(default=False)
    date_borrow = models.DateField(
        null=True, blank=True, help_text="Date when the item was borrowed"
    )
    date_return = models.DateField(
        null=True, blank=True, help_text="Date when the item is returned"
    )
    borrower = models.ForeignKey(
        Student, on_delete=models.CASCADE, null=True, blank=True
    )
    STATUS_CHOICES = [
        ("available", "Available"),
        ("borrowed", "Borrowed"),
    ]

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["parcel_id"], name="unique_parcel_id")
        ]

    def clean(self):
        if self.status:
            if not self.date_borrow or not self.date_return or not self.borrower:
                raise ValidationError(
                    "Both borrow and return dates are required when status is True."
                )
            if self.date_borrow > self.date_return:
                raise ValidationError("Borrow date cannot be after return date.")
        else:
            self.date_borrow = None
            self.date_return = None
            self.borrower = None

    def __str__(self):
        return f'Equipment: {self.name}, Status: {"Borrowed" if self.status else "Available"}'
<<<<<<< HEAD
=======
    
class Borrowing(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, to_field='equipment_id')
    borrower = models.ForeignKey(Student, on_delete=models.CASCADE)
    borrowed_on = models.DateTimeField(null=True, blank=True)
    returned_on = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.borrower.username} want to borrow {self.equipment}"
    
@receiver(connection_created)
def enforce_foreign_keys(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA foreign_keys = ON;')
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

Bowwing-Return-System/myproject/myapp/views.py
<<<<<<< HEAD
from django.shortcuts import render, redirect
from django.contrib import messages
from myapp.models import Student, Staff, Admin, Equipment, Status
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from .borrowing import BorrowingForm
from django.db.models import Q
from myapp.models import Equipment
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from .models import Student, Staff, Admin
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings
import random
import string

=======
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from myapp.models import Student, Staff, Admin, Equipment, Borrowing
from django.db.models import Q
from django.core.exceptions import ValidationError
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

def home(request):
    all_student = Student.objects.all()
    return render(request, "home.html", {"all_student": all_student})


def user_login(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

<<<<<<< HEAD
        kkumail = request.POST["kkumail"]
        password = request.POST["password"]

        for student in all_student:
            if kkumail == student.kkumail and password == student.password:
                return redirect("catalog_user")

        for staff in all_staff:
            if kkumail == staff.email and password == staff.password:
                return redirect("catalog_staff")

        for admin in all_admin:
            if kkumail == admin.email and password == admin.password:
                return redirect("catalog_admin")
            else:
                messages.error(request, "Your email or password is incorrect!")
                return redirect("login")

    return render(request, "login.html")

=======
        user = authenticate(request, email=email, password=password)
        print(user)
        if user is not None:
            try:
                if Admin.objects.get(email=user):
                    print("admin checked!")
                    login(request, user)
                    return redirect('catalog_admin')
            except:
                try:
                    if Staff.objects.get(email=user):
                        print("staff checked!")
                        login(request, user)
                        return redirect('catalog_staff')
                except:
                    try:    
                        if Student.objects.get(kkumail=user):
                                print("student checked!")
                                login(request, user)
                                return redirect('catalog_user')
                    except:
                        messages.error(request, 'Invalid credentials')

        return render(request, 'login.html', {'error': 'Invalid credentials'})

    return render(request, "login.html")

def user_logout(request):
    logout(request)
    return redirect('login')
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

def registor(request):
    if request.method == "POST":
        # get info
        fullname = request.POST["fullname"]
        username = request.POST["username"]
        kkumail = request.POST["kkumail"]
        phone = request.POST["phone"]
        password = request.POST["password"]
        student_id_edu = request.POST["student_id_edu"]
        major = request.POST["Major"]
        print(
            f"fullname: {fullname}\nusername: {username}\nkkumail: {kkumail}\nphone: {phone}\npassword: {password}\nstudent id: {student_id_edu}\nmajor: {major}"
        )

        # save info
        student = Student.objects.create(
            fullname=fullname,
            username=username,
            kkumail=kkumail,
            phone=phone,
            password=password,
            student_id_edu=student_id_edu,
            major=major,
        )
        student.save()
        return redirect("login")

    return render(request, "registor.html")

<<<<<<< HEAD

def catalog_user(request):
    all_equipment = Equipment.objects.all()
    all_status = Status.objects.all()
    selected_status = request.POST.get("filter")
=======
@login_required
def catalog_user(request):
    all_equipment = Equipment.objects.all()
    selected_status = request.POST.get('filter')
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540
    query = request.GET.get("q")
    print(selected_status)

    if query:
        all_equipment = all_equipment.filter(
            Q(name__icontains=query)
            | Q(brand__icontains=query)
            | Q(parcel_id__icontains=query)
        )

    if selected_status:
        if selected_status == "Unavailable":
            all_equipment = Equipment.objects.filter(status=True)
        elif selected_status == "Available":
            all_equipment = Equipment.objects.filter(status=False)
        else:
            all_equipment = Equipment.objects.all()

<<<<<<< HEAD
    return render(
        request,
        "user/catalog_user.html",
        {
            "all_equipment": all_equipment,
            "all_status": all_status,
            "selected_status": selected_status,
        },
    )
=======
    return render(request, "user/catalog_user.html", {
        "all_equipment": all_equipment,
        "selected_status": selected_status,
        })
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

@login_required
def catalog_staff(request):
    all_equipment = Equipment.objects.all()
<<<<<<< HEAD
    all_status = Status.objects.all()
    selected_status = request.POST.get("filter")
=======
    selected_status = request.POST.get('filter')
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540
    query = request.GET.get("q")
    print(selected_status)
    if query:
        all_equipment = all_equipment.filter(borrower__fullname__icontains=query)

    if selected_status:
        if selected_status == "Unavailable":
            all_equipment = Equipment.objects.filter(status=True)
        elif selected_status == "Available":
            all_equipment = Equipment.objects.filter(status=False)
        else:
            all_equipment = Equipment.objects.all()

<<<<<<< HEAD
    return render(
        request,
        "staff/catalog labstaff.html",
        {
            "all_equipment": all_equipment,
            "all_status": all_status,
            "selected_status": selected_status,
        },
    )

=======
    return render(request, "staff/catalog labstaff.html", {
        "all_equipment": all_equipment,
        "selected_status": selected_status,
        })
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

@login_required
def catalog_admin(request):
    devices = Equipment.objects.all()
    selected_status = request.POST.get('filter')
    query = request.GET.get("q")
    print(selected_status)
    if query:
        devices = devices.filter(borrower__fullname__icontains=query)

<<<<<<< HEAD

def borrow_view(request):
    form = BorrowingForm()
=======
    if selected_status:
        if selected_status == "Unavailable":
            devices = Equipment.objects.filter(status=True)
        elif selected_status == "Available":
            devices = Equipment.objects.filter(status=False)
        else:
            devices = Equipment.objects.all()
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

    return render(request, "admin1/catalog admin.html", {
        "devices": devices,
        "selected_status": selected_status,
        })
    # return render(request, "admin1/catalog admin.html", {"devices": devices})

<<<<<<< HEAD
    return render(
        request, "user/borrow_user.html", {"form": form, "products": products}
    )

=======
def borrow_view(request, equipment_id):
    equipment = Equipment.objects.get(equipment_id=equipment_id)
    if request.method == 'POST':
        date_borrow = request.POST.get('date_borrow')
        date_return = request.POST.get('date_return')
        all_borrow = Borrowing.objects.all()
        for borrow in all_borrow:
            if borrow.equipment == equipment and borrow.borrower == request.user:
                borrow.borrowed_on = date_borrow
                borrow.returned_on = date_return
                borrow.save()
                return redirect('catalog_user')
                
        borrow = Borrowing(equipment=equipment, borrower=request.user, borrowed_on=date_borrow, returned_on=date_return)
        borrow.save()
        return redirect('catalog_user')
    return render(request, 'user/borrow_user.html', {"equipment": equipment})
>>>>>>> 4d37d50192df075348887d69b36444bd3702e540

def home_staff(request):
    return render(request, "staff/home_staff.html")


def approval_staff(request):
    all_borrow = Borrowing.objects.all()
    return render(request, "staff/approval_staff.html", { "all_borrow": all_borrow })

def borrow_pass(request, borrow_id):
    borrow = Borrowing.objects.get(id=borrow_id)
    equipment = Equipment.objects.get(equipment_id=borrow.equipment.equipment_id)
    if request.method == "POST":
        if 'action' in request.POST:
            if request.POST['action'] == 'agree':
                print('pass', borrow_id)
                equipment.status = True
                equipment.date_borrow = borrow.borrowed_on
                equipment.date_return = borrow.returned_on
                equipment.borrower = borrow.borrower
                equipment.save()
                borrow.delete()

            elif request.POST['action'] == 'disagree':
                print('no pass', borrow_id)

Bowwing-Return-System/myproject/myapp/templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> 
    <link rel="stylesheet" href="{% static 'base_user.css' %}">
    {% block static %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>  
    <header>
        <div class="logo">
            <img src="{% static 'images/logo_empty.png' %}" alt="Logo">
            <div class="text-content">
                <span class="logo-letters">B <span style="color: red;">L</span> F</span>
                <div class="logo-subtext">Equipment borrowing</div>
                <div class="logo-subtext">System for Laboratory</div>
                <div class="logo-subtext">Facilities</div>
            </div>
        </div>
        
        <nav>
            <ul>
                <li><a href="{% url 'home_user' %}">HOME</a></li>
                <li><a href="{% url 'catalog_user' %}">CATALOG</a></li>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" id="logout-btn" class="logout-btn">Logout</button>
                </form>

            </ul>
        </nav>
    </header>

    {% block content %}
    {% endblock %}
</body>
</html>

Bowwing-Return-System/myproject/myapp/templates/user/borrow_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Borrowing</title>
</head>
<body>
    
    <a href="{% url 'home_user' %}">
        <button class="register-btn">Home</button>
    </a>
    <a href="{% url 'catalog_user' %}">
        <button class="register-btn">CATALOG</button>
    </a>
    <a href="{% url 'catalog_user' %}">
        <button class="register-btn">BACK</button>
    </a>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" id="logout-btn" class="logout-btn">Logout</button>
    </form>

    <form class="bd-example" method="post" action="">
        {% csrf_token %}
        <fieldset>
            <legend>Borrowing</legend>
            {%  if user.is_authenticated %}
                <h3>username: {{ user.username }}</h3>
            {% endif %}
            <label for="id_name" class="form-label">Equipment name: </label>
            <input type="text" value="{{ equipment.name }}" disabled></input>

            <label for="id_parcel_id" class="form-label">Parcel ID: </label>
            <input type="text" value="{{ equipment.parcel_id }}" disabled></input>
            
            <label for="id_brand" class="form-label">Brand: </label>
            <input type="text" value="{{ equipment.brand }}" disabled></input>

            <p>
                <label for="date_borrow">Borrowing date</label>
                <input type="date" name="date_borrow">

                <label for="date_return">Return date</label>
                <input type="date" name="date_return">
            </p>
          
            <button type="submit">Button submit</button>
        </fieldset>
    </form>
</body>
</html>

Bowwing-Return-System/myproject/myapp/templates/user/borrowing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Borrowing System</title>
    <link rel="stylesheet" href="{% static 'borrowing.css' %}">
</head>
<body>
    <div class="header">
        <div>
            <img src="logo.png" alt="Logo">
            <div style="display: inline-block; vertical-align: top; margin-left: 10px;">
                <h1>B L F</h1>
                <p>Equipment Borrowing System for Laboratory Facilities</p>
            </div>
        </div>
        <div class="nav-menu">
            <a href="#">HOME</a>
            <a href="#">CATALOG</a>
            <a href="#" class="active">BORROWING</a>
            <a href="#">STATUS</a>
        </div>
        <button class="back-button">BACK</button>
    </div>

    <div class="content">
        <div class="borrow-section">
            <h2>Borrow</h2>
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Chanjirawan Yongyean</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Chanjirawan Yongyean</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td></td>
                </tr>
                <tr>
                    <td>4</td>
                    <td></td>
                </tr>
                <tr>
                    <td>5</td>
                    <td></td>
                </tr>
            </table>
        </div>
        <button class="enter-button">ENTER</button>
    </div>
</body>
</html>

Bowwing-Return-System/myproject/myapp/templates/user/catalog_user.html
{% extends 'user/base.html' %}
{% load static %}

{% block static %}<link rel="stylesheet" href="{% static 'catalog_user.css' %}">{% endblock %}
{% block title %}Catalog for Borrowing{% endblock %}

{% block content %}
    <div class="container">
        <h1>Catalog for Borrowing</h1>
        <header>
            <div class="header-left">
                <form action="" method="get">
                    <input type="text" placeholder="Search..." id="search-bar" name="q" value="{{ request.GET.q|default_if_none:'' }}"
                        onkeydown="if(event.key === 'Enter'){ this.form.submit(); }">
                </form>

                <form action="" method="post">
                    {% csrf_token %}
                    <span>Status: </span>
                    <select id="status-dropdown" name="filter" onchange="this.form.submit();">
                        <option value="">All</option>
                        <option value="Available" {% if selected_status == 'Available' %}selected{% endif %}>Available</option>
                        <option value="Unavailable" {% if selected_status == 'Unavailable' %}selected{% endif %}>Unavailable</option>
                    </select>
                </form>
            </div>
        </header>

        <table>
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Picture</th>
                    <th scope="col">Equipment</th>
                    <th scope="col">Parcel ID</th>
                    <th scope="col">Brand</th>
                    <th scope="col">Date Borrow</th>
                    <th scope="col">Date Return</th>
                    <th scope="col">Borrow</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for equipment in all_equipment %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><img src="{{ equipment.image.url }}" alt="{{ equipment.name }}"></td>
                        <td>{{ equipment.name }}</td>
                        <td>{{ equipment.parcel_id }}</td>
                        <td>{{ equipment.brand }}</td>
                        <td>
                            {% if equipment.date_borrow %}
                                {{ equipment.date_borrow|date:"d-m-Y" }}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td>
                            {% if equipment.date_return %}
                                {{ equipment.date_return|date:"d-m-Y" }}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td>
                            {% if equipment.status %}
                                <button id="disabled-button" type="submit" disabled>Borrow</button>

                            {% else %}
                                <form action="{% url 'borrow_request' equipment.equipment_id %}" method="get">
                                    <button id="request-button" type="submit">Borrow</button>
                                </form>
                            
                            {% endif %}
                        </td>
                        <td>
                            {% if equipment.status %}
                                <span class="status unavailable">Unavailable</span>

                            {% else %}
                                <span class="status available">Available</span>
                            
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <script>
                function navigateToBorrow(equiment_id) {
                    window.location.href = '/user_borrowing/' + equiment_id ;
                }
            </script>
        </table>
    </div>
{% endblock %}